# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "qrcode"
client_id = "9d82ec3f2d3461fa283200724e6cb036"
application_url = "https://8766-166-1-22-239.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://8766-166-1-22-239.ngrok-free.app/auth/callback",
  "https://8766-166-1-22-239.ngrok-free.app/auth/shopify/callback",
  "https://8766-166-1-22-239.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "klaviyo-test-app.myshopify.com"
